prolog: "pipeline v0.3"
epilog: "(c) Kirill Baybekov"
input_dir: "Папка с исходными файлами"
output_dir: "Папка для результатов"
threads: "Количество потоков для анализа (16)"
trimmomatic_opts: "Опции для trimmomatic (SLIDINGWINDOW:4:18 HEADCROP:10 MINLEN:35)"
ref_fasta: "Путь к референсному файлу FASTA"
machine: "[medgen|local] Место запуска пайплайна"
sequence_mode: "[WES|WGS] Тип секвенирования (WES)"
modules: |
  [align|variant_calling|annotation|excel_postprocessing] Какой модуль запускать ("all"). 
  Возможные значения:
    - all: полный проход пайплайна
    - align: подготовка BAM-файлов
    - variant_calling: генерация VCF
    - annotation: аннотация вариантов
    - excel_postprocessing: постобработка файлов XLSX
exclude_samples: "Образцы для исключения из анализа (разделённые запятой)"
include_samples: "Образцы для включения в анализ (разделённые запятой)"
filter_common_variants: "Образцы, для которых включён фильтр по частоте"
freebayes_filters: "Фильтры для freebayes"
variant_filters: "Логическое выражение, используемое bcftools для фильтрации вариантов, полученных с помощью Freebayes и DeepVariant"
variant_frequency_threshold: "Значение частоты встречаемости варианта; варианты, встречающиеся выше указанного значения, в результаты включены не будут (0.15)"
debug: "[True] Тестовый запуск пайплайна; генерация логов с входными переменными и unix-командами"
project_path: "Путь к локальной конфигурации проекта"
cravat_annotators: "Список аннотаторов для cravat, указаывается через запятую"
subfolders: "[True] Поиск файлов в подпапках"