igor:
  threads: '16'
  ref_fasta: '/path/to/reference.fasta'
  stage: ['all']
  variant_frequency_threshold: '0.15'

  dir: /path/to/igor/folder
  cravat_annotators: clinvar clinvar_acmg omim ncbigene hpo hg19 gnomad spliceai cardioboost clinpred
  annovar_dir: /mnt/d/WES/database/annovar/

local:
  threads: '4'
  ref_fasta: /path/to/local/reference.fasta
  stage: 'all'
  variant_frequency_threshold: "0.15"

  dir: /path/to/local/folder
  cravat_annotators: clinvar omim hg19 gnomad
  annovar_dir: /home/user/WES/annovar/