project_path: ''
threads: '16'
ref_fasta: '/path/to/reference.fasta'
modules: ['align','variant_calling','annotation','excel_postprocessing']
variant_frequency_threshold: '0.15'
cravat_annotators: 'clinvar clinvar_acmg omim ncbigene hpo hg19 gnomad spliceai cardioboost clinpred'