cravat_annotators: >-
  clinvar clinvar_acmg omim ncbigene hpo hg19 gnomad gnomad4 spliceai cardioboost clinpred
freebayes_filters: >-
  --standard-filters --report-genotype-likelihood-max --min-coverage 8 --min-alternate-qsum 40 
  --min-alternate-count 2 --min-alternate-fraction 0.1
modules: ['align','variant_calling','annotation','excel_postprocessing']
ref_fasta: >-
  /mnt/d/WES/reference/Ensembl_hg38/Homo_sapiens.GRCh38.dna.primary_assembly.111.fa
seq_mode: >-
  WES
threads: >-
  16
trimmomatic_opts: >-
  SLIDINGWINDOW:4:18 HEADCROP:10 MINLEN:35
variant_frequency_threshold: >-
  0.15
variant_filters: >-
  "QUAL>18 && FORMAT/DP>16 && ((FORMAT/AD[0:1] / FORMAT/AD[0:0] > 0.2) || (FORMAT/AD[0:0] == 0 && FORMAT/AD[0:1] >= 3))"