global:
  filename: "sample.split('/')[-1]"
  basename: "{filename.split('_')[0]}_{filename.split('_')[1]}"
all:
  raw_fastqs: "[sample, sample.replace('_R1', '_R2')]"
  trim_galore_fastqs: "[s.replace({folders["input_dir"]}, {folders["tmp_dir"]}).replace('.fastq.gz', '_val_{({filenames["raw_fastqs"]}.index(s)+1)}.fq.gz') for s in {filenames["raw_fastqs"]}]"
  trimmomatic_fastqs: "' '.join(['{folders["tmp_dir"]}{filenames["basename"]}_{i}P.fq' for i in [1,2]])"
  abra_bam: "{folders['bam_dir']}{filenames['basename']}_abra2.bam"
  in_bam: "{folders['tmp_dir']}primary.bam"
  sorted_bam: "{folders['tmp_dir']}sorted.bam"
  vcf_freebayes: "{folders['vcf_dir']}{filenames['basename'}_freebayes.vcf"
  vcf_deepvariant: "{folders['vcf_dir']}{filenames['basename'}_deepvariant.vcf.gz"
  gvcf_deepvariant: "vcf_deepvariant.replace('vcf','gvcf')"
  annovar_vcf: "{folders['annotation_dir']}{filenames['basename'}_annovar"
align:
  raw_fastqs: "[sample, sample.replace('_R1', '_R2')]"
  trim_galore_fastqs: "[s.replace({folders["input_dir"]}, {folders["tmp_dir"]}).replace('.fastq.gz', '_val_{({filenames["raw_fastqs"]}.index(s)+1)}.fq.gz') for s in {filenames["raw_fastqs"]}]"
  trimmomatic_fastqs: "' '.join(['{folders["tmp_dir"]}{filenames["basename"]}_{i}P.fq' for i in [1,2]])"
  abra_bam: "{folders['bam_dir']}{filenames['basename']}_abra2.bam"
  in_bam: "{folders['tmp_dir']}primary.bam"
  sorted_bam: "{folders['tmp_dir']}sorted.bam"
variant_calling:
  abra_bam: "{folders['bam_dir']}{filenames['basename']}_abra2.bam"
  vcf_freebayes: "{folders['vcf_dir']}{filenames['basename'}_freebayes.vcf"
  vcf_deepvariant: "{folders['vcf_dir']}{filenames['basename'}_deepvariant.vcf.gz"
  gvcf_deepvariant: "vcf_deepvariant.replace('vcf','gvcf')"
annotation:
  annovar_vcf: "{folders['annotation_dir']}{filenames['basename'}_annovar"