medgen:
  envs:
    bcftools: "genetico"
    cravat: "cravat"
    fastqc: "genetico"
    freebayes: "genetico"
    trim_galore: "genetico"
    multiqc: "base"
    qualimap: "qualimap"
    
  binaries:
    abra2: "java -Xmx48G -jar /root/miniforge3/envs/genetico/share/abra2-2.24-1/abra2.jar"
    bcftools: "bcftools"
    bwa: bwa mem
    cravat: "oc"
    fastqc: "fastqc"
    freebayes: "freebayes"
    multiqc: "multiqc"
    qualimap: "qualimap"
    samblaster: "samblaster"
    samtools: "samtools"
    trim_galore: "trim_galore"
    trimmomatic: "/usr/share/java/trimmomatic-0.39.jar"
  env_command: "conda run -n env binary"

dell:
  envs:
    cravat: "cravat"
    trim_galore: "trim_galore"
    qualimap: "qualimap"
    abra2: "abra2"
    samblaster: "samblaster"
    trim_galore: "trim_galore"
    
  binaries:
    abra2: "abra2"
    bcftools: "bcftools"
    bwa: /home/data/Programms/BWA-MEME/bwa-meme mem
    cravat: "oc"
    fastqc: "fastqc"
    freebayes: "freebayes"
    multiqc: "multiqc"
    qualimap: "qualimap"
    samblaster: "samblaster"
    samtools: "samtools"
    trim_galore: "trim_galore"
    trimmomatic: "/usr/share/java/trimmomatic-0.39.jar"
  env_command: "mamba run -n env binary"