medgen:
  envs:
    cravat: "cravat"
    fastqc: "genetico"
    freebayes: "genetico"
    trim_galore: "genetico"
    multiqc: "base"
    qualimap: "qualimap"
    
  binaries:
    abra2: "-Xmx48G -jar /root/miniforge3/envs/genetico/share/abra2-2.24-1/abra2.jar"
    cravat: "oc"
    fastqc: "fastqc"
    freebayes: "freebayes"
    multiqc: "multiqc"
    qualimap: "qualimap"
    samblaster: "samblaster"
    samtools: "samtools"
    trim_galore: "trim_galore"
    trimmomatic: "/usr/share/java/trimmomatic-0.39.jar"
  env_command: "conda run -n env binary"