#TRIMMOMATIC IS OFF!

#RM TMP IS OFF!!!
# batch:       - remove_tmp_files after_batch: - remove_tmp_folder
sequence: ['align', 'variant_calling', 'annotation', 'excel_postprocessing']

align:
  module_before:
    none
  folders:
    input_dir:
    output_dir:
      log_dir:
        Logs
      tmp_dir:
        tmp
      qc_dir:
        QC
      fastqc_dir:
        QC/fastQC
      qualimap_dir:
        QC/qualimap
      bam_dir:
        bam
  
  source_extensions:
    ['1.fastq.gz', '1.fq.gz']

  filenames:
    filename: |
      os.path.basename(sample).split('.')[0]
    basename: |
      f"{filenames['filename'].split('_')[0]}_{filenames['filename'].split('_')[1]}"
    raw_fastqs: |
      [sample, sample.replace('_R1', '_R2')]
    trim_galore_fastqs: |
      [s.replace(folders['input_dir'], folders['tmp_dir']).replace('.fastq.gz', f"_val_{(filenames['raw_fastqs'].index(s)+1)}.fq.gz") for s in filenames['raw_fastqs']]
    trimmomatic_fastqs: |
      ' '.join([f"{folders['tmp_dir']}{filenames['basename']}_{i}P.fq" for i in [1,2]])
    abra_bam: |
      f"{folders['bam_dir']}{filenames['basename']}_abra2.bam"
    in_bam: |
      f"{folders['tmp_dir']}primary.bam"
    sorted_bam: |
      f"{folders['tmp_dir']}sorted.bam"

  commands:
    before_batch:
    sample_level:
      - trim_galore
      - aligning
      - samtools_sort
      - samtools_index
      - abra2
      - samtools_index_abra
      - qualimap
    after_batch:
      - fastqc_raw
      - multiqc

  result_dir: >-
    bam


variant_calling:
  module_before:
    align
  folders:
    input_dir:
      log_dir:
        Logs
      tmp_dir:
        tmp
      vcf_dir:
        vcf
    output_dir:
      
  
  source_extensions:
    ['.bam']
  
  filenames:
    filename: |
      os.path.basename(sample).split('.')[0]
    basename: |
      f"{filenames['filename'].split('_')[0]}_{filenames['filename'].split('_')[1]}"
    abra_bam: |
      f"{folders['input_dir']}{filenames['basename']}_abra2.bam"
    vcf_fb: |
      f"{folders['vcf_dir']}{filenames['basename']}_fb.vcf.gz"
    vcf_dv: |
      f"{folders['vcf_dir']}{filenames['basename']}_dv.vcf.gz"
    gvcf_dv: |
      f"{folders['vcf_dir']}{filenames['basename']}_dv.gvcf.gz"
    vcf: |
      f"{folders['vcf_dir']}{filenames['basename']}.vcf.gz"
    unzipped_vcf: |
      filenames['vcf'].removesuffix('.gz')

  commands:
    before_batch:
    sample_level:
      - freebayes
      - fb_bgzip_and_tabix
      - deepvariant
      - vcf_intersection
      - vcf_filtering
      - merged_vcf_actions
    after_batch:
  
  result_dir: >-
    vcf


annotation:
  module_before:
    variant_calling
  folders:
    input_dir:
      vcf_dir:
        vcf
    output_dir:
      log_dir:
        Logs
      tmp_dir:
        tmp
      ann_dir:
        annotation
  
  source_extensions:
    ['.vcf','.vcf.gz']
  
  filenames:
    filename: |
      os.path.basename(sample).split('.')[0]
    basename: |
      f"{filenames['filename'].split('_')[0]}_{filenames['filename'].split('_')[1]}"
    vcf: |
      f"{folders['vcf_dir']}{filenames['basename']}.vcf.gz"
  
  commands:
    before_batch:
    sample_level:
      - cravat
    after_batch:

  result_dir: >-
    annotation


excel_postprocessing:
  module_before:
    annotation
  folders:
    input_dir:
      ann_dir:
        annotation
    output_dir:
      log_dir:
        Logs
      tmp_dir:
        tmp
      excel_dir:
        excel
  
  source_extensions:
    ['.tsv']

  filenames:
    filename: |
      os.path.basename(sample).split('.')[0]
    basename: |
      f"{filenames['filename'].split('_')[0]}_{filenames['filename'].split('_')[1]}"
    cravat_tsv: |
      f"{sample}"
    excel: |
      f"{folders['excel_dir']}{filenames['basename']}.xlsx"
  
  commands:
    before_batch:
    sample_level:
      - excel_postprocessing
    after_batch:
