all:
  folders:
    input:
    output:
      log: "Log"
      tmp: "tmp"
      qc:  "QC"
      bam: "bam"
      vcf: "vcf"
      ann: "annotation"
      excel: "excel"
  extension: "_R1.fastq.gz"

align:
  folders:
    input:
    output:
      log: "Log"
      tmp: "tmp"
      qc:  "QC"
      bam: "bam"
  extension: "_R1.fastq.gz"

variant_calling:
  folders:
    input:
    output:
      log: "Log"
      tmp: "tmp"
      vcf: "vcf"
  extension: ".bam"

annotation:
  folders:
    input:
    output:
      log: "Log"
      tmp: "tmp"
      ann: "annotation"
  extension: ".vcf.gz"

excel_postprocessing:
  folders:
    input:
    output:
      log: "Log"
      tmp: "tmp"
      excel: "excel"
  extension: ".tsv"